"""link transactions to bank accounts

Revision ID: 2de2123575cc
Revises: cadd92db36b3
Create Date: 2026-08-10 20:32:14.249217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2de2123575cc'
down_revision: Union[str, Sequence[str], None] = 'cadd92db36b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('bank_account_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_expenses_bank_account_id'), 'expenses', ['bank_account_id'], unique=False)
    op.create_foreign_key(None, 'expenses', 'bank_accounts', ['bank_account_id'], ['id'], ondelete='SET NULL')
    op.add_column('incomes', sa.Column('bank_account_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_incomes_bank_account_id'), 'incomes', ['bank_account_id'], unique=False)
    op.create_foreign_key(None, 'incomes', 'bank_accounts', ['bank_account_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'incomes', type_='foreignkey')
    op.drop_index(op.f('ix_incomes_bank_account_id'), table_name='incomes')
    op.drop_column('incomes', 'bank_account_id')
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_index(op.f('ix_expenses_bank_account_id'), table_name='expenses')
    op.drop_column('expenses', 'bank_account_id')
    # ### end Alembic commands ###
