"""add profile image

Revision ID: 30da86f6a643
Revises: 448ab2f6c9df
Create Date: 2026-08-17 20:14:38.030194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30da86f6a643'
down_revision: Union[str, Sequence[str], None] = '448ab2f6c9df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('profile_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'profile_image')
    # ### end Alembic commands ###
