"""update expense table

Revision ID: 39fb0536903b
Revises: b3879bb6c214
Create Date: 2026-08-06 19:28:30.329151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39fb0536903b'
down_revision: Union[str, Sequence[str], None] = 'b3879bb6c214'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('payment_method', sa.String(length=50), nullable=False))
    op.add_column('expenses', sa.Column('bank_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'bank_name')
    op.drop_column('expenses', 'payment_method')
    # ### end Alembic commands ###
