"""add income table

Revision ID: b5a5a3a76d9f
Revises: dbf6115038dd
Create Date: 2026-08-06 12:54:56.340850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5a5a3a76d9f'
down_revision: Union[str, Sequence[str], None] = 'dbf6115038dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('verification_token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_users_email'), 'pending_users', ['email'], unique=True)
    op.create_index(op.f('ix_pending_users_id'), 'pending_users', ['id'], unique=False)
    op.create_index(op.f('ix_pending_users_verification_token'), 'pending_users', ['verification_token'], unique=True)
    op.create_table('income',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_income_id'), 'income', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_income_id'), table_name='income')
    op.drop_table('income')
    op.drop_index(op.f('ix_pending_users_verification_token'), table_name='pending_users')
    op.drop_index(op.f('ix_pending_users_id'), table_name='pending_users')
    op.drop_index(op.f('ix_pending_users_email'), table_name='pending_users')
    op.drop_table('pending_users')
    # ### end Alembic commands ###
