"""add bank name to income

Revision ID: bb5be9036019
Revises: 9e4ac735bfda
Create Date: 2026-08-05 19:57:29.529823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb5be9036019'
down_revision: Union[str, Sequence[str], None] = '9e4ac735bfda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incomes', sa.Column('bank_name', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incomes', 'bank_name')
    # ### end Alembic commands ###
