import { useEffect, useState } from "react";
import { Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { FaArrowTrendUp, FaChartColumn, FaChartPie, FaFileExcel, FaFilePdf, FaWallet } from "react-icons/fa6";
import { downloadReport, getAnalytics } from "../services/analyticsService";
import api from "../api/axios";
import "./Reports.css";
import "./Analytics.css";

const colors=["#6c4df6","#0f9f6e","#ec9a21","#df3f4f","#3182f6"];
const money=v=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(v||0);
const PeriodPicker=({period,setPeriod,exporting,onExport})=><div className="reports-actions"><label>Month<select value={period.month} onChange={e=>setPeriod(p=>({...p,month:+e.target.value}))}>{Array.from({length:12},(_,i)=><option key={i} value={i+1}>{new Date(2000,i).toLocaleString("en",{month:"long"})}</option>)}</select></label><label>Year<select value={period.year} onChange={e=>setPeriod(p=>({...p,year:+e.target.value}))}>{[period.year-1,period.year,period.year+1].map(y=><option key={y}>{y}</option>)}</select></label><button type="button" disabled={!!exporting} onClick={()=>onExport("pdf")}><FaFilePdf/>{exporting==="pdf"?"Preparing…":"Export PDF"}</button><button type="button" disabled={!!exporting} onClick={()=>onExport("excel")}><FaFileExcel/>{exporting==="excel"?"Preparing…":"Export Excel"}</button></div>;

export default function Analytics(){
 const now=new Date(),[period,setPeriod]=useState({month:now.getMonth()+1,year:now.getFullYear()}),[data,setData]=useState(),[error,setError]=useState(""),[exporting,setExporting]=useState("");
 const monthBounds=({month,year})=>({start_date:`${year}-${String(month).padStart(2,"0")}-01`,end_date:new Date(year,month,0).toISOString().slice(0,10)});
 const [range,setRange]=useState(()=>monthBounds({month:now.getMonth()+1,year:now.getFullYear()}));
 const [premiumData,setPremiumData]=useState(null),[premiumAccess,setPremiumAccess]=useState(false),[premiumError,setPremiumError]=useState("");
 useEffect(()=>{setData();setError("");getAnalytics(period).then(setData).catch(()=>setError("We could not load your analytics."));},[period]);
 useEffect(()=>setRange(monthBounds(period)),[period]);
 useEffect(()=>{api.get("/auth/me").then(({data:account})=>setPremiumAccess(account.role==="admin"||account.plan==="premium")).catch(()=>setPremiumAccess(false));},[]);
 useEffect(()=>{if(!premiumAccess)return;setPremiumData(null);setPremiumError("");api.get("/premium/insights",{params:range}).then(response=>setPremiumData(response.data)).catch(()=>setPremiumError("Detailed insights could not be loaded."));},[premiumAccess,range]);
 const onExport=async format=>{try{setExporting(format);await downloadReport(format,period);}catch{setError("The statement could not be downloaded.");}finally{setExporting("");}};
 if(error)return <div className="reports-message error">{error}</div>;if(!data)return <div className="reports-message">Loading your analytics…</div>;
 const {summary,categories,trend,goals}=data,top=categories[0],spent=summary.total_income?Math.round(summary.total_expenses/summary.total_income*100):0;
 const cashFlow=[{name:"Income",value:summary.total_income},{name:"Expenses",value:summary.total_expenses}].filter(item=>item.value>0);
 const insight=summary.net_balance<0?"Spending exceeded income. Start with your largest category.":summary.savings_rate>=20?"Your savings rate is healthy. Keep the momentum going.":"Your cash flow is positive; saving a little more can strengthen it.";
 return <div className="reports-page analytics-page">
  <header className="reports-hero"><div><p>Financial analytics</p><h1>Understand every rupee</h1><span>Discover spending patterns, cash-flow trends, and progress toward your goals.</span></div><PeriodPicker period={period} setPeriod={setPeriod} exporting={exporting} onExport={onExport}/><div className="reports-hero-rate"><span><FaArrowTrendUp/> Savings rate</span><strong>{summary.savings_rate}%</strong><small>{data.period.label}</small></div></header>
  <section className="reports-stat-grid"><article className="report-stat"><span>Net cash flow</span><strong>{money(summary.net_balance)}</strong><small>Income minus expenses</small></article><article className="report-stat income"><span>Income</span><strong>{money(summary.total_income)}</strong><small>{summary.income_count} credits</small></article><article className="report-stat expense"><span>Expenses</span><strong>{money(summary.total_expenses)}</strong><small>{summary.expense_count} debits</small></article><article className="report-stat category"><span>Top category</span><strong>{top?.category||"None"}</strong><small>{top?money(top.total):"No spending yet"}</small></article></section>
  <section className="reports-insight"><span className="reports-insight-icon"><FaArrowTrendUp/></span><div><p>Smart insight</p><strong>{insight}</strong></div><div className="reports-spend-rate"><span>Income spent</span><b>{spent}%</b><i><em style={{width:`${Math.min(spent,100)}%`}}/></i></div></section>
  <section className="reports-main-grid"><Chart title="Cash flow trend" subtitle="Income versus expenses over six months." icon={<FaWallet/>}><ResponsiveContainer width="100%" height={320}><LineChart data={trend}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="month"/><YAxis/><Tooltip formatter={money}/><Legend/><Line type="monotone" dataKey="income" stroke="#0f9f6e" strokeWidth={3}/><Line type="monotone" dataKey="expenses" stroke="#df3f4f" strokeWidth={3}/></LineChart></ResponsiveContainer></Chart><Chart title="Spending mix" subtitle="Share of expenses by category." icon={<FaChartPie/>}>{categories.length?<ResponsiveContainer width="100%" height={320}><PieChart><Pie data={categories} dataKey="total" nameKey="category" innerRadius={64} outerRadius={105}>{categories.map((x,i)=><Cell key={x.category} fill={colors[i%colors.length]}/>)}</Pie><Tooltip formatter={money}/><Legend/></PieChart></ResponsiveContainer>:<p className="reports-empty">No expense data yet.</p>}</Chart></section>
  <section className="analytics-chart-grid"><Chart title="Income vs expenses" subtitle="A pie-chart view of this month's cash flow." icon={<FaChartPie/>}>{cashFlow.length?<ResponsiveContainer width="100%" height={290}><PieChart><Pie data={cashFlow} dataKey="value" nameKey="name" outerRadius={100} label={({name,percent})=>`${name} ${(percent*100).toFixed(0)}%`}>{cashFlow.map((item,i)=><Cell key={item.name} fill={["#0f9f6e","#df3f4f"][i]}/>)}</Pie><Tooltip formatter={money}/><Legend/></PieChart></ResponsiveContainer>:<p className="reports-empty compact">No cash-flow data yet.</p>}</Chart><Chart title="Category comparison" subtitle="A bar graph of your highest-impact areas." icon={<FaChartColumn/>}>{categories.length?<ResponsiveContainer width="100%" height={290}><BarChart data={categories} layout="vertical"><CartesianGrid strokeDasharray="3 3" horizontal={false}/><XAxis type="number"/><YAxis dataKey="category" type="category" width={85}/><Tooltip formatter={money}/><Bar dataKey="total" fill="#6c4df6" radius={[0,7,7,0]}/></BarChart></ResponsiveContainer>:<p className="reports-empty compact">No categories to compare.</p>}</Chart></section>
  {premiumAccess&&<section className="analytics-detailed"><header className="statement-toolbar analytics-detailed-heading"><div><p>Detailed insights</p><h2>Custom-range analysis</h2><span>Compare spending and cash flow across a selected period, with a 12-month trend.</span></div><div className="reports-actions"><label>From<input type="date" value={range.start_date} onChange={event=>setRange(current=>({...current,start_date:event.target.value}))}/></label><label>To<input type="date" value={range.end_date} onChange={event=>setRange(current=>({...current,end_date:event.target.value}))}/></label></div></header>{premiumError?<p className="reports-message error">{premiumError}</p>:!premiumData?<p className="reports-message">Loading detailed insights...</p>:<><section className="reports-stat-grid"><article className="report-stat expense"><span>Expense change vs last month</span><strong>{premiumData.comparison.expense_change_percent}%</strong></article><article className="report-stat income"><span>Selected-range income</span><strong>{money(premiumData.summary.total_income)}</strong></article><article className="report-stat"><span>Selected-range expenses</span><strong>{money(premiumData.summary.total_expenses)}</strong></article><article className="report-stat"><span>Selected-range net</span><strong>{money(premiumData.summary.net_balance)}</strong></article></section><section className="reports-main-grid"><Chart title="12-month cash flow" subtitle="Long-term income and expense trends." icon={<FaWallet/>}><ResponsiveContainer width="100%" height={330}><LineChart data={premiumData.yearly_trend}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="month"/><YAxis/><Tooltip formatter={money}/><Legend/><Line type="monotone" dataKey="income" stroke="#0f9f6e" strokeWidth={3}/><Line type="monotone" dataKey="expenses" stroke="#df3f4f" strokeWidth={3}/></LineChart></ResponsiveContainer></Chart><Chart title="Selected-range categories" subtitle="Highest spending categories in your custom range." icon={<FaChartColumn/>}>{premiumData.categories.length?<ResponsiveContainer width="100%" height={330}><BarChart data={premiumData.categories}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="category"/><YAxis/><Tooltip formatter={money}/><Bar dataKey="total" fill="#6c4df6" radius={[7,7,0,0]}/></BarChart></ResponsiveContainer>:<p className="reports-empty">No expenses in this range.</p>}</Chart></section></>}</section>}
  <section className="analytics-lower"><article className="goal-report analytics-goals"><Heading title="Goal progress" subtitle="Your current savings targets." icon={<FaArrowTrendUp/>}/>{goals.length?<div className="goal-report-list">{goals.map(g=><div className="goal-report-item" key={g.id}><div><strong>{g.goal_name}</strong><span>{money(g.saved_amount)} of {money(g.target_amount)}</span></div><div className="goal-report-track"><span style={{width:`${g.progress_percentage}%`}}/></div><b>{g.progress_percentage.toFixed(0)}%</b></div>)}</div>:<p className="reports-empty compact">No savings goals yet.</p>}</article></section>
 </div>;
}
const Heading=({title,subtitle,icon})=><div className="report-card-heading"><div><span className="report-icon">{icon}</span><div><h2>{title}</h2><p>{subtitle}</p></div></div></div>;
const Chart=({title,subtitle,icon,children})=><article className="report-chart"><Heading title={title} subtitle={subtitle} icon={icon}/>{children}</article>;
