import { useEffect, useMemo, useState } from "react";
import { FaSearch, FaUserCog, FaUsers } from "react-icons/fa";
import api from "../api/axios";
import { getAdminOverview, getAdminUsers, updateUserAccess } from "../services/adminService";
import "./Admin.css";
import "./AdminEnhancements.css";

const money=(value)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(value||0);
export default function UserManagement(){
 const [users,setUsers]=useState([]),[query,setQuery]=useState(""),[saving,setSaving]=useState(""),[selected,setSelected]=useState(null),[error,setError]=useState("");
 useEffect(()=>{getAdminUsers().then(setUsers).catch(()=>setError("Could not load users."));},[]);
 const filtered=useMemo(()=>users.filter(user=>`${user.full_name} ${user.email} ${user.role} ${user.plan}`.toLowerCase().includes(query.toLowerCase())),[users,query]);
 const update=async(userId,field,value)=>{setSaving(`${userId}-${field}`);setError("");try{const changed=await updateUserAccess(userId,{[field]:value});setUsers(current=>current.map(user=>user.id===userId?changed:user));await getAdminOverview();}catch(requestError){setError(requestError.response?.data?.detail||"Could not update this user.");}finally{setSaving("");}};
 const inspect=async user=>{try{const response=await api.get(`/admin/users/${user.id}/financial-summary`);setSelected({...user,...response.data});}catch{setError("Could not load this user's financial summary.");}};
 return <main className="admin-page"><header><span><FaUserCog/> Admin control</span><h1>User management</h1><p>Search accounts, review access, and manage user status.</p></header>{error&&<p className="admin-error">{error}</p>}{selected&&<section className="admin-users admin-user-detail"><h2>{selected.full_name}</h2><button onClick={()=>setSelected(null)}>Close</button><div><span>Income <strong>{money(selected.income)}</strong></span><span>Expenses <strong>{money(selected.expenses)}</strong></span><span>Balance <strong>{money(selected.balance)}</strong></span><span>Records <strong>{selected.income_records+selected.expense_records}</strong></span></div></section>}<section className="admin-users"><div className="admin-section-head"><h2><FaUsers/> All users</h2><label><FaSearch/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search name, email, role"/></label></div><div className="admin-table-wrap"><table><thead><tr><th>User</th><th>Account</th><th>Subscription</th><th>Role</th><th>Financial data</th></tr></thead><tbody>{filtered.length?filtered.map(user=><tr key={user.id}><td><strong>{user.full_name}</strong><small>{user.email}</small></td><td><select value={user.is_active?"active":"inactive"} disabled={saving===`${user.id}-is_active`} onChange={event=>update(user.id,"is_active",event.target.value==="active")}><option value="active">Active</option><option value="inactive">Inactive</option></select></td><td>{user.plan==="premium"?"Premium":"Free"}</td><td><select value={user.role} disabled={saving===`${user.id}-role`} onChange={event=>update(user.id,"role",event.target.value)}><option value="user">User</option><option value="admin">Admin</option></select></td><td><button onClick={()=>inspect(user)}>View summary</button></td></tr>):<tr><td colSpan="5">No users match your search.</td></tr>}</tbody></table></div></section></main>;
}
